package arrays.binarysearch;

import java.util.Arrays;


/**
 * Problem: Generate Boolean Expression from an Integer Array
 *
 * Given integers, build a boolean expression over x that is true for exactly those values. This solution sorts the values and recursively joins equality checks with OR.
 *
 * Leetcode: none (related: https://leetcode.com/problems/summary-ranges/)
 * Pattern:  Divide and conquer | Expression construction | Balanced recursion
 *
 * Example:
 *   Input:  numbers = [1,3,4]
 *   Output: ((x == 1 || x == 3) || (x == 4))
 *   Why:    each listed number gets one equality check and OR accepts any of them.
 *
 * Follow-ups:
 *   1. Compress ranges? Emit x >= lo && x <= hi clauses for consecutive runs.
 *   2. Huge sets? Use intervals, decision diagrams, or generated bytecode instead of raw text.
 *   3. Support strings? Escape literals and consider trie-style sharing.
 *   4. Evaluate many x values? Use a HashSet rather than generated source text.
 *
 * Related: Summary Ranges (228).
 */
public class CreateExpression {

  public static void main(String[] args) {
    int[][] inputs = { {3, 1, 4}, {5}, {} };
    String[] expected = { "((x == 1 || x == 3) || (x == 4))", "(x == 5)", "" };
    for (int i = 0; i < inputs.length; i++) {
      int[] numbers = inputs[i].clone();
      String got = buildBooleanExpression(numbers);
      System.out.printf("numbers=%s -> \"%s\"  expected=\"%s\"%n", Arrays.toString(inputs[i]), got, expected[i]);
    }
  }


  /**
   * Entry point for test execution.
   */


    /**
   * Intuition: Each allowed number becomes one equality leaf, and OR accepts any leaf. Sorting makes output deterministic, then balanced recursion avoids a long one-sided expression.
   *
   * Algorithm:
   *   1. Return an empty string for null or empty input.
   *   2. Sort the numbers.
   *   3. Recursively build equality leaves and join halves with OR.
   *
   * Time:  O(n log n) - sorting dominates expression building.
   * Space: O(log n) - balanced recursion depth, excluding the result string.
   *
   * @param numbers values that should make the expression true
   * @return boolean expression over x
   */
  public static String buildBooleanExpression(int[] numbers) {
    if (numbers == null || numbers.length == 0) {
      return "";  // Edge case: empty input
    }

    Arrays.sort(numbers); // Ensure deterministic structure
    return constructExpression(numbers, 0, numbers.length - 1);
  }

    /** Builds a balanced OR expression for sortedNumbers[start..end]. */
  private static String constructExpression(int[] sortedNumbers, int start, int end) {
    if (start == end) {
      return "(x == " + sortedNumbers[start] + ")";
    }

    if (end - start == 1) {
      return "(x == " + sortedNumbers[start] + " || x == " + sortedNumbers[end] + ")";
    }

    int mid = start + (end - start) / 2;
    String leftExpression = constructExpression(sortedNumbers, start, mid);
    String rightExpression = constructExpression(sortedNumbers, mid + 1, end);

    return "(" + leftExpression + " || " + rightExpression + ")";
  }
}
