package dynamicprogramming;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * Problem: Is Subsequence (LeetCode #392)
 *
 * Problem Statement:
 * Given two strings 'source' and 'target', return true if 'source' is a subsequence of 'target',
 * or false otherwise. A subsequence of a string is a new string generated by deleting some
 * (can be none) of the characters without changing the relative order of the remaining characters.
 *
 * Example 1:
 * Input: source = "abc", target = "ahbgdc"
 * Output: true
 *
 * Example 2:
 * Input: source = "axc", target = "ahbgdc"
 * Output: false
 *
 * Approach:
 * We can solve this problem using a two-pointer technique. We'll use one pointer to traverse
 * the source string and another to traverse the target string. For each character in the source,
 * we'll try to find a matching character in the target string. If we can find all characters
 * of the source in order within the target, then source is a subsequence of target.
 *
 * Time Complexity: O(n) where n is the length of the target string
 * Space Complexity: O(1) - We only use constant extra space
 *
 * Follow-up Questions:
 * 1. What if there are lots of incoming source strings, say s1, s2, ..., sk where k >= 10^9?
 *    Answer: We can preprocess the target string to create a map of each character to the list
 *    of indices where it appears. Then for each source string, we can perform a binary search
 *    to find the next occurrence of each character in the target string.
 *
 * 2. How would you modify your solution if you need to check multiple source strings against the same target?
 *    Answer: We can preprocess the target string once and then use the same preprocessed data
 *    to efficiently check multiple source strings. This would involve creating a map from characters
 *    to their sorted list of indices in the target string.
 *
 * 3. What if the target string is very large and the source strings are small?
 *    Answer: The two-pointer approach is already optimal for this case as it only needs to scan
 *    the target string once per source string. For very large targets, we could consider using
 *    the binary search approach mentioned in the first follow-up.
 *
 * LeetCode: https://leetcode.com/problems/is-subsequence/
 */
public class IsSubsequence {

    /**
     * Checks if 'source' is a subsequence of 'target' using two pointers
     *
     * @param source The potential subsequence to check
     * @param target The target string to check against
     * @return true if source is a subsequence of target, false otherwise
     */
    public boolean isSubsequence(String source, String target) {
        // If source is empty, it's always a subsequence
        if (source.isEmpty()) {
            return true;
        }

        int sourceIndex = 0;
        int targetIndex = 0;

        // Traverse both strings
        while (sourceIndex < source.length() && targetIndex < target.length()) {
            // If characters match, move to next character in source
            if (source.charAt(sourceIndex) == target.charAt(targetIndex)) {
                sourceIndex++;
            }
            // Always move to next character in target
            targetIndex++;
        }

        // If we've gone through all characters in source, it's a subsequence
        return sourceIndex == source.length();
    }

    /**
     * Follow-up solution for checking multiple source strings against the same target
     * This solution preprocesses the target string for efficient lookups
     */
    public boolean isSubsequenceOptimized(String source, String target) {
        // Preprocess the target string to create a map of character to list of indices
        // where each character appears in the target string
        Map<Character, List<Integer>> charToIndices = new HashMap<>();

        // Populate the map with character indices
        for (int i = 0; i < target.length(); i++) {
            char c = target.charAt(i);
            if (!charToIndices.containsKey(c)) {
                charToIndices.put(c, new ArrayList<>());
            }
            charToIndices.get(c).add(i);
        }

        int prevIndex = -1; // To keep track of the last matched index in target

        for (char c : source.toCharArray()) {
            // If the character doesn't exist in target, source can't be a subsequence
            if (!charToIndices.containsKey(c)) {
                return false;
            }

            // Find the first occurrence of c in target that comes after prevIndex
            List<Integer> indices = charToIndices.get(c);
            int insertionPoint = Collections.binarySearch(indices, prevIndex + 1);

            // If the exact value is not found, binarySearch returns (-(insertion point) - 1)
            if (insertionPoint < 0) {
                insertionPoint = -insertionPoint - 1;
            }

            // If no such index exists, source is not a subsequence
            if (insertionPoint == indices.size()) {
                return false;
            }

            // Update prevIndex to the found index
            prevIndex = indices.get(insertionPoint);
        }

        return true;
    }

    /**
     * Alternative solution using Java's built-in indexOf method
     * This is more concise but may be slightly less efficient for very large inputs
     */
    public boolean isSubsequenceUsingIndexOf(String source, String target) {
        int currentIndex = -1;

        for (char c : source.toCharArray()) {
            // Find the next occurrence of c in target after currentIndex
            currentIndex = target.indexOf(c, currentIndex + 1);

            // If character not found, source is not a subsequence
            if (currentIndex == -1) {
                return false;
            }
        }

        return true;
    }
}
